/**
 * OpenRouter API Wrapper
 * Connects to OpenRouter to access various AI models (like Gemini Pro, Llama 3)
 */

// WARNING: In a production app, you should proxy requests through your own backend
// to hide the API key. We are using it client-side here for the MVP.
const OPENROUTER_API_KEY = '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';
const API_URL = 'https://openrouter.ai/api/v1/chat/completions';

// Free models available on OpenRouter
export const FREE_MODELS = [
    { id: 'openrouter/free', name: 'OpenRouter Auto (Best Free)' },
    { id: 'meta-llama/llama-3.3-70b-instruct:free', name: 'Llama 3.3 70B (Reliable)' },
    { id: 'google/gemma-3-27b-it:free', name: 'Gemma 3 27B (Creative)' },
    { id: 'mistralai/mistral-small-3.1-24b-instruct:free', name: 'Mistral Small 24B (Solid)' }
];

// Default to a verified free model
const DEFAULT_MODEL = FREE_MODELS[0].id;

// Security: Basic client-side rate limit (e.g. 50 requests per day)
const MAX_REQUESTS_PER_DAY = 50;

function checkRateLimit() {
    const today = new Date().toDateString();
    const storedData = localStorage.getItem('tf_api_usage');
    let usage = storedData ? JSON.parse(storedData) : { date: today, count: 0 };

    // Reset if it's a new day
    if (usage.date !== today) {
        usage = { date: today, count: 0 };
    }

    // Check limit
    if (usage.count >= MAX_REQUESTS_PER_DAY) {
        throw new Error(`Daily limit reached (${MAX_REQUESTS_PER_DAY} requests). Please try again tomorrow.`);
    }

    // Increment and save
    usage.count++;
    localStorage.setItem('tf_api_usage', JSON.stringify(usage));
}

/**
 * Call the OpenRouter API
 * @param {string} systemPrompt - Instructions for the AI
 * @param {string} userMessage - The user's input text
 * @param {string} [model] - Optional specific model to use (defaults to gemini flash)
 * @returns {Promise<string>} The AI's response text
 */
export async function callAI(systemPrompt, userMessage, model = DEFAULT_MODEL) {
    try {
        checkRateLimit();

        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
                'HTTP-Referer': window.location.origin, // Required by OpenRouter
                'X-Title': 'TextForge Tools', // Optional
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: model,
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userMessage }
                ]
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`API Error (${response.status}): ${errorData.error?.message || 'Unknown error'}`);
        }

        const data = await response.json();

        if (data.choices && data.choices.length > 0) {
            return data.choices[0].message.content;
        } else {
            throw new Error('No response generated by AI');
        }

    } catch (error) {
        console.error('OpenRouter API call failed:', error);
        throw error;
    }
}
